name: ci
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: changes
        shell: bash
        run: |
          set -euo pipefail
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            base="${{ github.event.pull_request.base.sha }}"; head="${{ github.event.pull_request.head.sha }}"
          else
            base="${{ github.event.before }}"; head="${{ github.sha }}"
          fi
          git fetch --no-tags --depth=1 origin "$base" || true
          files=$(git diff --name-only "$base" "$head" || true)
          echo "Changed files:"; echo "$files"
          allow_re='^(\.gitignore|.*\.md|docs/.*)$'
          skip=true
          if [ -z "$files" ]; then skip=false; fi
          while IFS= read -r f; do [[ -z "$f" ]] && continue; [[ ! "$f" =~ $allow_re ]] && skip=false && break; done <<< "$files"
          echo "skip=${skip}" >> $GITHUB_OUTPUT
      - name: docs-only; mark ci passed
        if: steps.changes.outputs.skip == 'true'
        run: echo "Docs/.gitignore-only change — skipping tests."
      - uses: actions/setup-python@v5
        if: steps.changes.outputs.skip != 'true'
        with: { python-version: "3.10" }
      - name: install tesseract
        if: steps.changes.outputs.skip != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr
      - name: run tests strictly
        if: steps.changes.outputs.skip != 'true'
        run: |
          set -euo pipefail
          python -m venv .venv
          source .venv/bin/activate
          pip install -q --upgrade pip
          pip install -q pytest coverage ruff==0.6.9 mypy==1.11.1 junitparser types-Pillow==10.2.0.20240520
          pip install -q -r requirements.txt
          mkdir -p .handoff
          pytest --junitxml=.handoff/tests.xml -ra --strict-markers --strict-config
          coverage run -m pytest -q
          coverage xml -o .handoff/coverage.xml
      - uses: actions/upload-artifact@v4
        if: steps.changes.outputs.skip != 'true'
        with: { name: handoff, path: .handoff }
